name: flutter_app
description: "Stickman Run game (stickman running + obstacles)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cactus_obstacle.png
    - assets/images/spike_obstacle.png
    - assets/images/stalagmite_obstacle.png
    - assets/images/rollingrock_obstacle.png
    - assets/images/drone_obstacle.png
    - assets/images/laser_obstacle.png
    - assets/images/bat_obstacle.png
    - assets/images/firejet_obstacle.png
    - assets/images/fireball_obstacle.png
    - assets/images/pendulummine_obstacle.png
    - assets/sprites/coin.png
    - assets/sprites/magnet.png
    - assets/sprites/shield.png
    - assets/sprites/stickman_run_1.png
    - assets/sprites/stickman_run_2.png
    - assets/sprites/stickman_run_3.png
    - assets/sprites/stickman_run_4.png
    - assets/sprites/stickman_run_5.png
    - assets/sprites/stickman_run_6.png
    - assets/sprites/stickman_attack_1.png
    - assets/sprites/stickman_attack_2.png
    - assets/sprites/stickman_attack_3.png
    - assets/sprites/stickman_attack_4.png
    - assets/sprites/stickman_attack_5.png
    - assets/sprites/stickman_attack_6.png
    - assets/sprites/stickman_attack_7.png
    - assets/sprites/stickman_attack_8.png
    - assets/sprites/stickman_crawl_1.png
    - assets/sprites/stickman_crawl_2.png
    - assets/sprites/stickman_crawl_3.png
    - assets/sprites/stickman_crawl_4.png
    - assets/sprites/stickman_crawl_5.png
    - assets/sprites/stickman_crawl_6.png
    - assets/sprites/stickman_crawl_7.png
    - assets/sprites/stickman_crawl_8.png
    - assets/sprites/stickman_crawl_9.png
    - assets/sprites/stickman_crawl_10.png
    - assets/sprites/stickman_crawl_11.png
    - assets/sprites/stickman_crawl_12.png
    - assets/images/forest_background.png
    - assets/images/desert_background.png
    - assets/images/nightcity_background.png
    - assets/images/darkcave_background.png
    - assets/images/volcano_background.png
