name: flutter_app
description: "Stickman Run game (stickman running + obstacles)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cactus_obstacle.png
    - assets/images/spike_obstacle.png
    - assets/images/stalagmite_obstacle.png
    - assets/images/rollingrock_obstacle.png
    - assets/images/drone_obstacle.png
    - assets/images/laser_obstacle.png
    - assets/images/bat_obstacle.png
    - assets/images/firejet_obstacle.png
    - assets/images/fireball_obstacle.png
    - assets/images/pendulummine_obstacle.png
